---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: default
data:
  traefik.toml: |
    [Global]
      checkNewVersion = true
      sendAnonymousUsage = true
    [accessLog]
    # [log]
    #   level = "debug"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
      [entryPoints.tcp]
        address = ":8081"
    [providers]
      [providers.kubernetesCRD]
    [api]
      dashboard = true
