---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: tcp
              containerPort: 8081
            - name: admin
              containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik
            - name: mtls-creds
              mountPath: /secrets
      volumes:
        - name: config-volume
          configMap:
            name: traefik-config
        - name: mtls-creds
          secret:
            secretName: mtls-creds
