---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: path
  namespace: playground
  annotations:
    kubernetes.io/ingress.class: traefik-ninja
  labels:
    tier: frontend
spec:
  entryPoints:
    - http
  routes:
    - match: PathPrefix(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
