---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-foo
  namespace: playground
spec:
  addPrefix:
    prefix: /foo
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: known-ips
  namespace: playground
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.1.7
      - 127.0.0.1/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: latency-check
  namespace: playground
spec:
  circuitBreaker:
    expression: LatencyAtQuantileMS(50.0) > 100
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-compress
  namespace: playground
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-whoami
  namespace: playground
spec:
  stripPrefix:
    prefixes:
      - /whoami
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secured
  namespace: playground
spec:
  chain:
    middlewares:
      - playground/known-ips
      - playground/add-foo
