---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-foo
  namespace: playground
spec:
  addPrefix:
    prefix: /foo
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: known-ips
  namespace: playground
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.1.7
      - 127.0.0.1/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: latency-check
  namespace: playground
spec:
  circuitBreaker:
    expression: LatencyAtQuantileMS(50.0) > 100
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-compress
  namespace: playground
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-whoami
  namespace: playground
spec:
  stripPrefix:
    prefixes:
      - /whoami
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secured
  namespace: playground
spec:
  chain:
    middlewares:
      - playground/known-ips
      - playground/add-foo
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-errorpage
  namespace: playground
spec:
  errors:
    status:
      - 500-599
    query: /{status}
    service: playground/path-ingress-d027988890c9025cffce
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-forward-auth-without-tls
  namespace: playground
spec:
  forwardAuth:
    address: http://whoami.playground.svc.cluster.local/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-User
      - X-Secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-forward-auth-mtls
  namespace: playground
spec:
  forwardAuth:
    address: https://whoamimtls.playground.svc.cluster.local/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-User
      - X-Secret
    tls:
      ca: /secrets/ca.cert
      caOptional: false
      cert: /secrets/client.cert
      key: /secrets/client.key
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-header
  namespace: playground
spec:
  headers:
    stsSeconds: 3500
    forceSTSHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-inflightreq
  namespace: playground
spec:
  inFlightReq:
    amount: 1
    sourceCriterion:
      ipStrategy:
        excludedIPs:
          - 127.0.0.1/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-passtlsclientcert
  namespace: playground
spec:
  passTLSClientCert:
    pem: true
    info:
      notAfter: true
      notBefore: true
      sans: true
      subject:
        country: true
        province: true
        locality: true
        organization: true
        commonName: true
        serialNumber: true
        domainComponent: true
      issuer:
        country: true
        province: true
        locality: true
        organization: true
        commonName: true
        serialNumber: true
        domainComponent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-ratelimit
  namespace: playground
spec:
  rateLimit:
    average: 100
    burst: 50
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirect-to-whoami
  namespace: playground
spec:
  redirectRegex:
    regex: ^http://whoami.docker\.localhost/foo(.*)
    replacement: http://whoami.docker.localhost/bar${1}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirect-to-https
  namespace: playground
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: 44434
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-force-path-bar
  namespace: playground
spec:
  replacePath:
    path: /bar
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-replace-path-foo-bar
  namespace: playground
spec:
  replacePathRegex:
    regex: ^/foo/(.*)
    replacement: /bar/$1
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-retry
  namespace: playground
spec:
  retry:
    attempts: 4
