---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: enable-mutual-tls
  namespace: playground
spec:
  minVersion: VersionTLS12
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
      - whoami.mtls.docker.localhost
